# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 15:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistemaacademico', '0002_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.DecimalField(decimal_places=2, max_digits=3)),
                ('nota2', models.DecimalField(decimal_places=2, max_digits=3)),
                ('nota3', models.DecimalField(decimal_places=2, max_digits=3)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaacademico.Disciplina')),
            ],
        ),
    ]
