# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaacademico', '0004_auto_20161011_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacoes',
            options={'permissions': (('view_notas', 'View notas'),)},
        ),
    ]
