# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaacademico', '0005_auto_20161012_0505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacoes',
            options={'permissions': (('readonly', 'Can Read only Avaliacoes'),)},
        ),
    ]
